### ISSUE TITLE
blessed subs are no longer blessed when passed through module_installed

### ISSUE THREAD

**Issue by dakkar** [rjbs/Sub-Exporter-ForMethods#1]
The code in `module_installer` wraps coderefs; if the original coderefs were blessed, the new ones won't be. This cause breakage downstream of `MooseX::Types::Structured` (see https://rt.cpan.org/Ticket/Display.html?id=103247 ) because `MooseX::Types` expects type subs to be blessed in a special package.
Something equivalent to the code in the patch attached to that RT ticket should probably be integrated in `module_installer` to make sure we don't lose blessedness anywhere.

**Comment by karenetheridge** [comment]
I could have sworn this came up a year or so ago, somewhere else...

at any rate, I can't reproduce the error on my end, where I'm running the most recent versions of everything.. so this feels like something that has been fixed already, if I can figure out what and where.

**Comment by rjbs** [comment]
Thanks, I have added a `rebless` option to `method_installer` in v0.100052

**Comment by karenetheridge** [comment]
Woohoo. For the record, The problem I was struggling to remember in April was the lack of blessing that was needed in MooseX::Types -- which I implemented manually in version 0.44, and now can be removed in favour of using this new option.
